# Adding dog to bycicle
python launch.py --config configs/add.yaml --train --gpu 1 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply system.inpaint_prompt="a dog on the bench" system.refine_prompt="make it a dog" system.cache_overwrite=False system.cache_dir="add_dog"  trainer.max_steps=1

python launch.py --config configs/add.yaml --train --gpu 1 data.source=/home/scur2198/cv2/GaussianEditor/dataset/kitchen system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/kitchen/point_cloud/iteration_7000/point_cloud.ply system.inpaint_prompt="sand on the table" system.refine_prompt="make it sand" system.cache_overwrite=False system.cache_dir="add_dog"  trainer.max_steps=1

python launch.py --config configs/add.yaml --train --gpu 1 data.source=/home/scur2198/cv2/GaussianEditor/dataset/room system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/room/point_cloud/iteration_7000/point_cloud.ply system.inpaint_prompt="a mouse under the piano" system.refine_prompt="make it a mouse" system.cache_overwrite=False system.cache_dir="add_dog"  trainer.max_steps=1

# Deleting tractor from kitchen in 2 point-cloud resolutions
python launch.py --config configs/del-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.fix_holes=True system.inpaint_scale=1 system.mask_dilate=15 system.max_densify_percent=0.01 system.anchor_weight_init_g0=0 system.anchor_weight_init=0.0 system.anchor_weight_multiplier=1.5 system.seg_prompt="tractor" system.loss.lambda_anchor_color=5 system.loss.lambda_anchor_geo=50 system.loss.lambda_anchor_scale=50 system.loss.lambda_anchor_opacity=50 system.densify_from_iter=0 system.densify_until_iter=5000 system.densification_interval=50 data.source=/home/scur2198/cv2/GaussianEditor/dataset/kitchen system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/kitchen/point_cloud/iteration_7000/point_cloud.ply system.cache_overwrite=False system.inpaint_prompt="table, carpet"

python launch.py --config configs/del-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.fix_holes=True system.inpaint_scale=1 system.mask_dilate=15 system.max_densify_percent=0.01 system.anchor_weight_init_g0=0 system.anchor_weight_init=0.0 system.anchor_weight_multiplier=1.5 system.seg_prompt="bicycle" system.loss.lambda_anchor_color=5 system.loss.lambda_anchor_geo=50 system.loss.lambda_anchor_scale=50 system.loss.lambda_anchor_opacity=50 system.densify_from_iter=0 system.densify_until_iter=5000 system.densification_interval=50 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply system.cache_overwrite=False system.inpaint_prompt="grass, bench"

python launch.py --config configs/del-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.fix_holes=True system.inpaint_scale=1 system.mask_dilate=15 system.max_densify_percent=0.01 system.anchor_weight_init_g0=0 system.anchor_weight_init=0.0 system.anchor_weight_multiplier=1.5 system.seg_prompt="tractor" system.loss.lambda_anchor_color=5 system.loss.lambda_anchor_geo=50 system.loss.lambda_anchor_scale=50 system.loss.lambda_anchor_opacity=50 system.densify_from_iter=0 system.densify_until_iter=5000 system.densification_interval=50 data.source=/home/scur2198/cv2/GaussianEditor/dataset/kitchen system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/kitchen/point_cloud/iteration_30000/point_cloud.ply system.cache_overwrite=False system.inpaint_prompt="table, carpet"

python launch.py --config configs/del-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.fix_holes=True system.inpaint_scale=1 system.mask_dilate=15 system.max_densify_percent=0.01 system.anchor_weight_init_g0=0 system.anchor_weight_init=0.0 system.anchor_weight_multiplier=1.5 system.seg_prompt="vase" system.loss.lambda_anchor_color=5 system.loss.lambda_anchor_geo=50 system.loss.lambda_anchor_scale=50 system.loss.lambda_anchor_opacity=50 system.densify_from_iter=0 system.densify_until_iter=5000 system.densification_interval=50 data.source=/home/scur2198/cv2/GaussianEditor/dataset/garden system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/garden/point_cloud/iteration_7000/point_cloud.ply system.cache_overwrite=False system.inpaint_prompt="table, flowers"

python launch.py --config configs/del-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.fix_holes=True system.inpaint_scale=1 system.mask_dilate=15 system.max_densify_percent=0.01 system.anchor_weight_init_g0=0 system.anchor_weight_init=0.0 system.anchor_weight_multiplier=1.5 system.seg_prompt="statue" system.loss.lambda_anchor_color=5 system.loss.lambda_anchor_geo=50 system.loss.lambda_anchor_scale=50 system.loss.lambda_anchor_opacity=50 system.densify_from_iter=0 system.densify_until_iter=5000 system.densification_interval=50 data.source=/home/scur2198/cv2/GaussianEditor/dataset/garden system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/garden/point_cloud/iteration_7000/point_cloud.ply system.cache_overwrite=False system.inpaint_prompt="wall, bush"

python launch.py --config configs/del-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.fix_holes=True system.inpaint_scale=1 system.mask_dilate=15 system.max_densify_percent=0.01 system.anchor_weight_init_g0=0 system.anchor_weight_init=0.0 system.anchor_weight_multiplier=1.5 system.seg_prompt="glasses" system.loss.lambda_anchor_color=5 system.loss.lambda_anchor_geo=50 system.loss.lambda_anchor_scale=50 system.loss.lambda_anchor_opacity=50 system.densify_from_iter=0 system.densify_until_iter=5000 system.densification_interval=50 data.source=/home/scur2198/cv2/GaussianEditor/dataset/room system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/room/point_cloud/iteration_7000/point_cloud.ply system.cache_overwrite=False system.inpaint_prompt="table"

# Make the grass on fire with different difusion models, different point-cloud resolutions and different parameters
python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="grass" system.prompt_processor.prompt="make the grass on fire"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply

python launch.py --config configs/edit-n2n.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="grass" system.prompt_processor.prompt="make the grass on fire"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply

python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="grass" system.prompt_processor.prompt="make the grass on fire"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-n2n.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="grass" system.prompt_processor.prompt="make the grass on fire"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="grass" system.prompt_processor.prompt="make the grass on fire"  system.max_densify_percent=0.1 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply

python launch.py --config configs/edit-n2n.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="grass" system.prompt_processor.prompt="make the grass on fire"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=3.0  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=100 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply

python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="bicyle" system.prompt_processor.prompt="make the bike bigger"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-n2n.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="bicycle" system.prompt_processor.prompt="make it a stone bicycle"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/bicycle/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="ball" system.prompt_processor.prompt="make it a basketball"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/garden system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/garden/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="table" system.prompt_processor.prompt="make it snowy"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/garden system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/garden/point_cloud/iteration_7000/point_cloud.ply

python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="statue" system.prompt_processor.prompt="turn buddha into einstein"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/garden system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/garden/point_cloud/iteration_7000/point_cloud.ply

python launch.py --config configs/edit-ctn.yaml --train --gpu 0 trainer.max_steps=2000 system.cache_dir="ground_fire" system.seg_prompt="bottle" system.prompt_processor.prompt="make it a coca-cola bottle"  system.max_densify_percent=0.01 system.anchor_weight_init_g0=1 system.anchor_weight_init=0.5 system.anchor_weight_multiplier=1.5  system.loss.lambda_anchor_color=0 system.loss.lambda_anchor_geo=5 system.loss.lambda_anchor_scale=5 system.loss.lambda_anchor_opacity=0 system.densify_from_iter=100 system.densify_until_iter=5000 system.densification_interval=300 data.source=/home/scur2198/cv2/GaussianEditor/dataset/room system.gs_source=/home/scur2198/cv2/GaussianEditor/dataset/room/point_cloud/iteration_7000/point_cloud.ply